### ISSUE TITLE
[BUG]: Incorrect key prevents experienceLevel filter from working in search

### ISSUE THREAD

**Issue by SapirKro** [AIHawk-app/Auto_Jobs_Applier#696]
### Describe the Bug

In the `src/aihawk_job_manager.py` file, the `get_base_search_url` function incorrectly references the `experience_level` key instead of the correct `experienceLevel` key when extracting values. As a result, the experience level filter does not function as intended during search operations. Instead of returning the expected list of experience levels, the function returns an empty list. This issue hinders the ability to filter job searches based on the specified experience levels.

### Steps to reproduce

1. Go to `data_folder/config.yaml` file.
2. Update the `experienceLevel` section to ensure that at least one value is set to true.
For example:
   ```yaml
   experienceLevel:
     internship: true
     entry: true
     associate: true
     mid-senior level: true
     director: false
     executive: false
   ```

### Expected behavior

The `experience_levels` list in should contain indices for the `True` values in `experienceLevel`, allowing the search functionality to filter based on experience levels.

### Actual behavior

The `experience_levels` list is empty due to the incorrect key, which prevents the `experienceLevel` filter from applying correctly during a search.

### Branch

main

### Python version

Python 3.12.7

### LLM Used

gemini

### Model used

gemini-pro
